### ISSUE TITLE
Needing to actually pass null

### ISSUE THREAD

**Issue by alchemyjamie** [brielov/dnull#59]
Hey - thanks for putting together this package - very useful!  I have a case where I need to _actually_ pass null to find all cases where a relation _does not_ exist.  

prisma supports `model.findMany({ where: { relationshipname: null } })`, but this lib would turn that null to an undefined.

Have you thought about a way to pass a null and ensure it persists?

**Comment by brielov** [comment]
That's a good question. I haven't thought of that. Can you think of any solution / API change that can be implemented for this scenario?
