### ISSUE TITLE
Possible bad build for 1.0.1?

### ISSUE THREAD

**Issue by orta** [brielov/dnull#65]
Is it possible that something happened during the new build - it looks like all three files reference a file which doesn't exist in the fs:

![image](https://user-images.githubusercontent.com/49038/187072841-ca296d56-58be-4c59-9a69-5008ef0ee9f7.png)

The 1.0.0 release for comparison:

![image](https://user-images.githubusercontent.com/49038/187073058-966de306-05c8-41c5-8366-585078089b9c.png)

**Comment by brielov** [comment]
@orta Just published a patch release with a few improvements, including fixing the build problem. Thanks for reporting!

**Comment by orta** [comment]
Thanks!
